// Login 
export const  ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const  ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS,'
export const  ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'


export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE';

export const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

export const UPDATE_EXPENSE_STATUS_REQUEST = 'UPDATE_EXPENSE_STATUS_REQUEST';
export const UPDATE_EXPENSE_STATUS_SUCCESS = 'UPDATE_EXPENSE_STATUS_SUCCESS';
export const UPDATE_EXPENSE_STATUS_FAILURE = 'UPDATE_EXPENSE_STATUS_FAILURE';

// EXPENSE FILTERING (Admin)
export const SET_EXPENSE_FILTER = 'SET_EXPENSE_FILTER';

// CHARTS (Insights - Admin only)
export const FETCH_CATEGORY_EXPENSES_SUCCESS = 'FETCH_CATEGORY_EXPENSES_SUCCESS';
export const FETCH_MONTHLY_EXPENSES_SUCCESS = 'FETCH_MONTHLY_EXPENSES_SUCCESS';

// AUDIT LOGS
export const LOG_ACTION = 'LOG_ACTION';

// Fetch audit logs

export const FETCH_AUDIT_LOGS_REQUEST = 'FETCH_AUDIT_LOGS_REQUEST';
export const FETCH_AUDIT_LOGS_SUCCESS = 'FETCH_AUDIT_LOGS_SUCCESS';
export const FETCH_AUDIT_LOGS_FAILURE = 'FETCH_AUDIT_LOGS_FAILURE';


// Total expenses per category

export const TOTAL_EXPENSES_REQUEST = 'TOTAL_EXPENSES_REQUEST'
export const TOTAL_EXPENSES_SUCCESS = 'TOTAL_EXPENSES_SUCCESS'
export const TOTAL_EXPENSES_FAILURE = 'TOTAL_EXPENSES_FAILURE'


// Expense Over Time


export const EXPENSE_OVER_TIME_REQUEST = 'EXPENSE_OVER_TIME_REQUEST';
export const EXPENSE_OVER_TIME_SUCCESS = 'EXPENSE_OVER_TIME_SUCCESS';
export const EXPENSE_OVER_TIME_FAILURE = 'EXPENSE_OVER_TIME_FAILURE';
