// Register
export const  REGISTER_REQUEST =  'REGISTER_REQUEST'
export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const  REGISTER_FAILURE = 'REGISTER_FAILURE'

// Login 
export const  LOGIN_REQUEST = 'LOGIN_REQUEST'
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS,'
export const  LOGIN_FAILURE = 'LOGIN_FAILURE'


export const LOGOUT = 'LOGOUT'

export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILURE = 'ADD_EXPENSE_FAILURE';

export const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

export const UPDATE_EXPENSE_STATUS_REQUEST = 'UPDATE_EXPENSE_STATUS_REQUEST';
export const UPDATE_EXPENSE_STATUS_SUCCESS = 'UPDATE_EXPENSE_STATUS_SUCCESS';
export const UPDATE_EXPENSE_STATUS_FAILURE = 'UPDATE_EXPENSE_STATUS_FAILURE';

// EXPENSE FILTERING (Admin)
export const SET_EXPENSE_FILTER = 'SET_EXPENSE_FILTER';

// CHARTS (Insights - Admin only)
export const FETCH_CATEGORY_EXPENSES_SUCCESS = 'FETCH_CATEGORY_EXPENSES_SUCCESS';
export const FETCH_MONTHLY_EXPENSES_SUCCESS = 'FETCH_MONTHLY_EXPENSES_SUCCESS';

// AUDIT LOGS
export const LOG_ACTION = 'LOG_ACTION';

export const FETCH_AUDIT_LOGS_REQUEST = 'FETCH_AUDIT_LOGS_REQUEST';
export const FETCH_AUDIT_LOGS_SUCCESS = 'FETCH_AUDIT_LOGS_SUCCESS';
export const FETCH_AUDIT_LOGS_FAILURE = 'FETCH_AUDIT_LOGS_FAILURE';
